"""added spray season

Revision ID: 02f1349212e3
Revises: 5ce06bff7d74
Create Date: 2026-05-21 13:29:15.418836

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "02f1349212e3"
down_revision: Union[str, Sequence[str], None] = "5ce06bff7d74"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spray_seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("season_start", sa.Date(), nullable=False),
        sa.Column("season_end", sa.Date(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spray_seasons_date_created"),
        "spray_seasons",
        ["date_created"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spray_seasons_is_archived"),
        "spray_seasons",
        ["is_archived"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spray_seasons_is_current"),
        "spray_seasons",
        ["is_current"],
        unique=False,
    )
    op.add_column(
        "spray_programs", sa.Column("spray_season_id", sa.Integer(), nullable=True)
    )
    op.drop_index(op.f("ix_spray_programs_year_end"), table_name="spray_programs")
    op.drop_index(op.f("ix_spray_programs_year_start"), table_name="spray_programs")
    op.create_index(
        op.f("ix_spray_programs_spray_season_id"),
        "spray_programs",
        ["spray_season_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "spray_programs", "spray_seasons", ["spray_season_id"], ["id"]
    )

    # --- data migration ---
    bind = op.get_bind()

    # Insert default season and get its ID in one step
    result = bind.execute(
        sa.text("""
            INSERT INTO spray_seasons (name, season_start, season_end, is_current, is_archived, date_created)
            VALUES ('Spray Season 25/26', '2025-07-01', '2026-06-30', true, false, now())
            RETURNING id
        """)
    )
    season_id = result.scalar()

    # Assign all existing spray programs to the default season
    bind.execute(
        sa.text("UPDATE spray_programs SET spray_season_id = :season_id").bindparams(
            season_id=season_id
        )
    )

    # Now safe to make spray_season_id non-nullable
    op.alter_column("spray_programs", "spray_season_id", nullable=False)
    # --- end data migration ---

    op.drop_column("spray_programs", "year_end")
    op.drop_column("spray_programs", "year_start")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spray_programs",
        sa.Column("year_start", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "spray_programs",
        sa.Column("year_end", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "spray_programs", type_="foreignkey")
    op.drop_index(
        op.f("ix_spray_programs_spray_season_id"), table_name="spray_programs"
    )
    op.create_index(
        op.f("ix_spray_programs_year_start"),
        "spray_programs",
        ["year_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_spray_programs_year_end"), "spray_programs", ["year_end"], unique=False
    )
    op.drop_column("spray_programs", "spray_season_id")
    op.drop_index(op.f("ix_spray_seasons_is_current"), table_name="spray_seasons")
    op.drop_index(op.f("ix_spray_seasons_is_archived"), table_name="spray_seasons")
    op.drop_index(op.f("ix_spray_seasons_date_created"), table_name="spray_seasons")
    op.drop_table("spray_seasons")
    # ### end Alembic commands ###
