"""added SprayProgramChemicals table 3

Revision ID: 067fe534194c
Revises: 098918ee102a
Create Date: 2025-07-01 14:13:25.823885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '067fe534194c'
down_revision: Union[str, Sequence[str], None] = '098918ee102a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spray_record_chemicals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spray_record_id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.Column('batch_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemicals.id'], ),
    sa.ForeignKeyConstraint(['spray_record_id'], ['spray_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_users_created_date'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_table('users')
    op.drop_constraint(op.f('fk_spray_program_chemicals_spray_record_id'), 'spray_program_chemicals', type_='foreignkey')
    op.drop_column('spray_program_chemicals', 'spray_record_id')
    op.drop_column('spray_program_chemicals', 'batch_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spray_program_chemicals', sa.Column('batch_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('spray_program_chemicals', sa.Column('spray_record_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_spray_program_chemicals_spray_record_id'), 'spray_program_chemicals', 'spray_records', ['spray_record_id'], ['id'], ondelete='CASCADE')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_created_date'), 'users', ['created_date'], unique=False)
    op.drop_table('spray_record_chemicals')
    # ### end Alembic commands ###
