"""added active ingredient unit ENUM

Revision ID: 07b02536db59
Revises: 10d8fcd15b1d
Create Date: 2025-09-10 16:22:21.030897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07b02536db59'
down_revision: Union[str, Sequence[str], None] = '10d8fcd15b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_ingredients', sa.Column('active_ingredient_unit', postgresql.ENUM('GL', 'GKG', name='activeingredientunit', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_ingredients', 'active_ingredient_unit')
    # ### end Alembic commands ###
