"""created new table Active Ingredients and moved max_el and min_days_before harvest to that table

Revision ID: 10d8fcd15b1d
Revises: 2652496a75e4
Create Date: 2025-09-10 15:08:36.026376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '10d8fcd15b1d'
down_revision: Union[str, Sequence[str], None] = '2652496a75e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemicals_max_el_id'), table_name='chemicals')
    op.drop_constraint(op.f('chemicals_max_el_id_fkey'), 'chemicals', type_='foreignkey')
    op.drop_column('chemicals', 'max_el_id')
    op.drop_column('chemicals', 'min_days_before_harvest')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemicals', sa.Column('min_days_before_harvest', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chemicals', sa.Column('max_el_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chemicals_max_el_id_fkey'), 'chemicals', 'growth_stages', ['max_el_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chemicals_max_el_id'), 'chemicals', ['max_el_id'], unique=False)
    # ### end Alembic commands ###
