"""removed test enum column from Chemical

Revision ID: 12d5e80e2cd1
Revises: 7e017bcffe67
Create Date: 2025-06-26 12:23:42.699850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '12d5e80e2cd1'
down_revision: Union[str, Sequence[str], None] = '7e017bcffe67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
