"""changed var name field to unique

Revision ID: 140e919e9799
Revises: a6f645baea9c
Create Date: 2025-06-20 15:33:26.498113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '140e919e9799'
down_revision: Union[str, Sequence[str], None] = 'a6f645baea9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_managementunit_name'), 'managementunit', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_managementunit_name'), table_name='managementunit')
    # ### end Alembic commands ###
