"""Moved target field to SprayChemical

Revision ID: 22b715e735ed
Revises: bdc9cfc18136
Create Date: 2025-06-26 13:09:03.633982

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "22b715e735ed"
down_revision: Union[str, Sequence[str], None] = "bdc9cfc18136"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_date"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_last_login"), table_name="users")
    op.drop_table("users")
    op.drop_column("chemicals", "target")
    op.add_column(
        "spray_program_chemicals",
        sa.Column(
            "target",
            postgresql.ENUM(
                "RUST_MITE",
                "BUD_MITE",
                "BOTRYTIS",
                "DOWNY_MILDEW",
                "NUTRITION",
                "POWDERY_BOT",
                "POWDERY",
                "WETTER",
                name="target",
                create_type=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spray_program_chemicals", "target")
    op.add_column(
        "chemicals",
        sa.Column(
            "target",
            postgresql.ENUM(
                "RUST_MITE",
                "BUD_MITE",
                "BOTRYTIS",
                "DOWNY_MILDEW",
                "NUTRITION",
                "POWDERY_BOT",
                "POWDERY",
                "WETTER",
                name="target",
                create_type=False,
            ),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_last_login"), "users", ["last_login"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_created_date"), "users", ["created_date"], unique=False
    )
    # ### end Alembic commands ###
