"""made spray name not nullable, added unique constraint for spray name for a spray program

Revision ID: 25ffdb884ba2
Revises: 4fb4c050adb4
Create Date: 2025-07-29 10:04:56.094344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '25ffdb884ba2'
down_revision: Union[str, Sequence[str], None] = '4fb4c050adb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_spray_name_per_program', 'sprays', ['name', 'spray_program_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_spray_name_per_program', 'sprays', type_='unique')
    # ### end Alembic commands ###
