"""added max_el_id and min_days_before_harvest to Chemical

Revision ID: 2652496a75e4
Revises: 8aa4b9fe86b7
Create Date: 2025-09-10 13:59:12.882694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2652496a75e4'
down_revision: Union[str, Sequence[str], None] = '8aa4b9fe86b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemicals', sa.Column('max_el_id', sa.Integer(), nullable=True))
    op.add_column('chemicals', sa.Column('min_days_before_harvest', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chemicals_max_el_id'), 'chemicals', ['max_el_id'], unique=False)
    op.create_foreign_key(None, 'chemicals', 'growth_stages', ['max_el_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chemicals', type_='foreignkey')
    op.drop_index(op.f('ix_chemicals_max_el_id'), table_name='chemicals')
    op.drop_column('chemicals', 'min_days_before_harvest')
    op.drop_column('chemicals', 'max_el_id')
    # ### end Alembic commands ###
