"""Added Chemical Groups Table

Revision ID: 2b5d70927df3
Revises: 4a55756fbad0
Create Date: 2025-06-26 15:15:00.282635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b5d70927df3'
down_revision: Union[str, Sequence[str], None] = '4a55756fbad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_date'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_table('users')
    op.add_column('chemical_groups', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('chemical_groups', sa.Column('type', postgresql.ENUM('FUNGICIDE', 'HERBICIDE', 'INSECTICIDE', 'OTHER', name='chemicalgrouptype', create_type=False), nullable=False))
    op.add_column('chemical_groups', sa.Column('moa', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_chemical_groups_code'), 'chemical_groups', ['code'], unique=False)
    op.create_index(op.f('ix_chemical_groups_name'), 'chemical_groups', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chemical_groups_name'), table_name='chemical_groups')
    op.drop_index(op.f('ix_chemical_groups_code'), table_name='chemical_groups')
    op.drop_column('chemical_groups', 'moa')
    op.drop_column('chemical_groups', 'type')
    op.drop_column('chemical_groups', 'code')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_created_date'), 'users', ['created_date'], unique=False)
    # ### end Alembic commands ###
