"""Added ondelete cascade to SprayRecord and SpratyProgramChemical, and cascade_delete to SprayProgram

Revision ID: 3854777a3d53
Revises: 22b715e735ed
Create Date: 2025-06-26 13:56:34.665127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3854777a3d53'
down_revision: Union[str, Sequence[str], None] = '22b715e735ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_date'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_table('users')
    op.drop_constraint(op.f('spray_program_chemicals_spray_program_id_fkey'), 'spray_program_chemicals', type_='foreignkey')
    op.create_foreign_key(None, 'spray_program_chemicals', 'spray_programs', ['spray_program_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('spray_records_spray_program_id_fkey'), 'spray_records', type_='foreignkey')
    op.create_foreign_key(None, 'spray_records', 'spray_programs', ['spray_program_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spray_records', type_='foreignkey')
    op.create_foreign_key(op.f('spray_records_spray_program_id_fkey'), 'spray_records', 'spray_programs', ['spray_program_id'], ['id'])
    op.drop_constraint(None, 'spray_program_chemicals', type_='foreignkey')
    op.create_foreign_key(op.f('spray_program_chemicals_spray_program_id_fkey'), 'spray_program_chemicals', 'spray_programs', ['spray_program_id'], ['id'])
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_created_date'), 'users', ['created_date'], unique=False)
    # ### end Alembic commands ###
