"""moved to new vine_testing db

Revision ID: 38c8d571d5ae
Revises: 2637cdb7bed3
Create Date: 2025-06-24 10:36:08.097750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38c8d571d5ae'
down_revision: Union[str, Sequence[str], None] = '2637cdb7bed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
