"""Made relationship between spray_program and spray many-to-many 2

Revision ID: 3da638faa6be
Revises: 9b1aa03af6df
Create Date: 2025-07-17 10:59:23.207794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3da638faa6be'
down_revision: Union[str, Sequence[str], None] = '9b1aa03af6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
