"""added many to one rel between User(operator) and SprayRecord

Revision ID: 46aa92d6706b
Revises: 3da638faa6be
Create Date: 2025-07-17 13:29:28.811638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '46aa92d6706b'
down_revision: Union[str, Sequence[str], None] = '3da638faa6be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spray_records', sa.Column('operator_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_spray_records_operator_id'), 'spray_records', ['operator_id'], unique=False)
    op.create_foreign_key(None, 'spray_records', 'users', ['operator_id'], ['id'])
    op.drop_column('spray_records', 'operator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spray_records', sa.Column('operator', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'spray_records', type_='foreignkey')
    op.drop_index(op.f('ix_spray_records_operator_id'), table_name='spray_records')
    op.drop_column('spray_records', 'operator_id')
    # ### end Alembic commands ###
