"""Added song

Revision ID: 48dacb5144b2
Revises: f8f60848dda8
Create Date: 2025-06-17 17:02:38.672204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '48dacb5144b2'
down_revision: Union[str, Sequence[str], None] = 'f8f60848dda8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vineyard', 'contact_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vineyard', sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
