"""added status table

Revision ID: 4d1ee2a1c7da
Revises: fa20a2d65436
Create Date: 2025-06-20 15:19:40.580467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d1ee2a1c7da'
down_revision: Union[str, Sequence[str], None] = 'fa20a2d65436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managementunit', sa.Column('date_planted', sa.Date(), nullable=True))
    op.add_column('managementunit', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'managementunit', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managementunit', type_='foreignkey')
    op.drop_column('managementunit', 'status_id')
    op.drop_column('managementunit', 'date_planted')
    # ### end Alembic commands ###
