"""Added MU

Revision ID: 51b173572aac
Revises: 48dacb5144b2
Create Date: 2025-06-17 17:11:05.822042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '51b173572aac'
down_revision: Union[str, Sequence[str], None] = '48dacb5144b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_column('managementunit', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managementunit', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table('song',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('artist', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('song_pkey'))
    )
    # ### end Alembic commands ###
