"""Initial migration

Revision ID: 52292000d2f6
Revises:
Create Date: 2025-07-17 08:41:19.249753

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52292000d2f6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spray_programs", sa.Column("year_start", sa.Integer(), nullable=False)
    )
    op.add_column("spray_programs", sa.Column("year_end", sa.Integer(), nullable=False))
    op.drop_index(op.f("ix_spray_programs_year"), table_name="spray_programs")
    op.create_index(
        op.f("ix_spray_programs_year_end"), "spray_programs", ["year_end"], unique=False
    )
    op.create_index(
        op.f("ix_spray_programs_year_start"),
        "spray_programs",
        ["year_start"],
        unique=False,
    )
    op.drop_column("spray_programs", "year")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
