"""added withholding_period to Chemicals

Revision ID: 5ce06bff7d74
Revises: 63da76d29e20
Create Date: 2026-02-04 11:12:17.021649

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ce06bff7d74"
down_revision: Union[str, Sequence[str], None] = "63da76d29e20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chemicals",
        sa.Column(
            "withholding_period", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chemicals", "withholding_period")
    # ### end Alembic commands ###
