"""added note field to SprayRecord

Revision ID: 63da76d29e20
Revises: c6714bb209e1
Create Date: 2025-10-14 10:10:56.536205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '63da76d29e20'
down_revision: Union[str, Sequence[str], None] = 'c6714bb209e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spray_records', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spray_records', 'note')
    # ### end Alembic commands ###
