"""added enum columns to Chemical

Revision ID: 7e017bcffe67
Revises: b91e86f28278
Create Date: 2025-06-26 12:22:58.205798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e017bcffe67'
down_revision: Union[str, Sequence[str], None] = 'b91e86f28278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('OPEN', 'CLOSED', name='taskstatus').create(op.get_bind())
    op.add_column('chemicals', sa.Column('status', postgresql.ENUM('OPEN', 'CLOSED', name='taskstatus', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemicals', 'status')
    sa.Enum('OPEN', 'CLOSED', name='taskstatus').drop(op.get_bind())
    # ### end Alembic commands ###
