"""added unique constraint to spray_program_id and chemical_id pairs in SprayProgramChemical

Revision ID: 82bcde2beb5f
Revises: 8edfd1b61de0
Create Date: 2025-07-02 15:27:02.802623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82bcde2beb5f'
down_revision: Union[str, Sequence[str], None] = '8edfd1b61de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sprayprogram_chemical', 'spray_program_chemicals', ['spray_program_id', 'chemical_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sprayprogram_chemical', 'spray_program_chemicals', type_='unique')
    # ### end Alembic commands ###
