"""added mu field

Revision ID: 85dd46bf82dc
Revises: 140e919e9799
Create Date: 2025-06-20 15:39:16.551998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85dd46bf82dc'
down_revision: Union[str, Sequence[str], None] = '140e919e9799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managementunit', sa.Column('variety_name_modifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('managementunit', 'variety_name_modifier')
    # ### end Alembic commands ###
