"""added reentry table and relationship to chemical

Revision ID: 8aa4b9fe86b7
Revises: a5a9fa63ab26
Create Date: 2025-09-10 12:57:03.542943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8aa4b9fe86b7'
down_revision: Union[str, Sequence[str], None] = 'a5a9fa63ab26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chemical_reentrys')
    op.add_column('chemical_reentry_link', sa.Column('reentry_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chemical_reentry_link_chemical_id'), 'chemical_reentry_link', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_chemical_reentry_link_reentry_id'), 'chemical_reentry_link', ['reentry_id'], unique=False)
    op.drop_constraint(op.f('chemical_reentry_link_reentry_period_id_fkey'), 'chemical_reentry_link', type_='foreignkey')
    op.drop_constraint(op.f('chemical_reentry_link_chemical_id_fkey'), 'chemical_reentry_link', type_='foreignkey')
    op.create_foreign_key(None, 'chemical_reentry_link', 'reentry_period', ['reentry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chemical_reentry_link', 'chemicals', ['chemical_id'], ['id'], ondelete='CASCADE')
    op.drop_column('chemical_reentry_link', 'reentry_period_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemical_reentry_link', sa.Column('reentry_period_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chemical_reentry_link', type_='foreignkey')
    op.drop_constraint(None, 'chemical_reentry_link', type_='foreignkey')
    op.create_foreign_key(op.f('chemical_reentry_link_chemical_id_fkey'), 'chemical_reentry_link', 'chemicals', ['chemical_id'], ['id'])
    op.create_foreign_key(op.f('chemical_reentry_link_reentry_period_id_fkey'), 'chemical_reentry_link', 'reentry_period', ['reentry_period_id'], ['id'])
    op.drop_index(op.f('ix_chemical_reentry_link_reentry_id'), table_name='chemical_reentry_link')
    op.drop_index(op.f('ix_chemical_reentry_link_chemical_id'), table_name='chemical_reentry_link')
    op.drop_column('chemical_reentry_link', 'reentry_id')
    op.create_table('chemical_reentrys',
    sa.Column('chemical_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reentry_period_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemicals.id'], name=op.f('chemical_reentrys_chemical_id_fkey')),
    sa.ForeignKeyConstraint(['reentry_period_id'], ['reentry_period.id'], name=op.f('chemical_reentrys_reentry_period_id_fkey')),
    sa.PrimaryKeyConstraint('chemical_id', 'reentry_period_id', name=op.f('chemical_reentrys_pkey'))
    )
    # ### end Alembic commands ###
