"""added unique constraint to spray_record_id and chemical_id pairs in SprayRecordChemical

Revision ID: 8edfd1b61de0
Revises: 252858c22199
Create Date: 2025-07-02 15:23:52.853850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8edfd1b61de0'
down_revision: Union[str, Sequence[str], None] = '252858c22199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sprayrecord_chemical', 'spray_record_chemicals', ['spray_record_id', 'chemical_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sprayrecord_chemical', 'spray_record_chemicals', type_='unique')
    # ### end Alembic commands ###
