"""added role enum to User

Revision ID: 8ff179339ce4
Revises: b67f0ae4bb90
Create Date: 2025-07-10 13:17:00.522571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ff179339ce4'
down_revision: Union[str, Sequence[str], None] = 'b67f0ae4bb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('SUPERADMIN', 'ADMIN', 'OPERATOR', 'USER', name='userrole', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
