"""Made relationship between spray_program and spray many-to-many

Revision ID: 9b1aa03af6df
Revises: 52292000d2f6
Create Date: 2025-07-17 10:52:17.652886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9b1aa03af6df'
down_revision: Union[str, Sequence[str], None] = '52292000d2f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sprays_spray_program_id_fkey'), 'sprays', type_='foreignkey')
    op.drop_column('sprays', 'spray_program_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sprays', sa.Column('spray_program_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('sprays_spray_program_id_fkey'), 'sprays', 'spray_programs', ['spray_program_id'], ['id'])
    # ### end Alembic commands ###
