"""Added Chemical Groups with m-m relationship with Chemicals

Revision ID: 9e0f498ec5b8
Revises: 12d5e80e2cd1
Create Date: 2025-06-26 12:38:21.273137

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9e0f498ec5b8"
down_revision: Union[str, Sequence[str], None] = "12d5e80e2cd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("OPEN", "CLOSED", name="taskstatus").create(op.get_bind())
    op.add_column(
        "chemicals",
        sa.Column(
            "status",
            postgresql.ENUM("OPEN", "CLOSED", name="taskstatus", create_type=False),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "chemicals", type_="foreignkey")
    op.drop_column("chemicals", "chem_group_id")
    op.drop_table("chemical_group_link")
    op.drop_table("chemical_groups")
    # ### end Alembic commands ###
