"""removed clone from vars table

Revision ID: 9fad5d858d31
Revises: a1d085e5b9c0
Create Date: 2025-06-20 19:34:01.366076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9fad5d858d31'
down_revision: Union[str, Sequence[str], None] = 'a1d085e5b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variety', 'clone_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variety', sa.Column('clone_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
