"""added index to all foreign keys

Revision ID: a5a9fa63ab26
Revises: 25ffdb884ba2
Create Date: 2025-08-11 13:24:57.692669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5a9fa63ab26'
down_revision: Union[str, Sequence[str], None] = '25ffdb884ba2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chemical_group_link_chemical_id'), 'chemical_group_link', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_chemical_group_link_group_id'), 'chemical_group_link', ['group_id'], unique=False)
    op.create_index(op.f('ix_management_units_status_id'), 'management_units', ['status_id'], unique=False)
    op.create_index(op.f('ix_management_units_variety_id'), 'management_units', ['variety_id'], unique=False)
    op.create_index(op.f('ix_management_units_vineyard_id'), 'management_units', ['vineyard_id'], unique=False)
    op.create_index(op.f('ix_spray_chemicals_chemical_id'), 'spray_chemicals', ['chemical_id'], unique=False)
    op.create_index(op.f('ix_spray_chemicals_spray_id'), 'spray_chemicals', ['spray_id'], unique=False)
    op.create_index(op.f('ix_spray_records_growth_stage_id'), 'spray_records', ['growth_stage_id'], unique=False)
    op.create_index(op.f('ix_sprays_growth_stage_id'), 'sprays', ['growth_stage_id'], unique=False)
    op.create_index(op.f('ix_sprays_spray_program_id'), 'sprays', ['spray_program_id'], unique=False)
    op.create_index(op.f('ix_varieties_wine_colour_id'), 'varieties', ['wine_colour_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_varieties_wine_colour_id'), table_name='varieties')
    op.drop_index(op.f('ix_sprays_spray_program_id'), table_name='sprays')
    op.drop_index(op.f('ix_sprays_growth_stage_id'), table_name='sprays')
    op.drop_index(op.f('ix_spray_records_growth_stage_id'), table_name='spray_records')
    op.drop_index(op.f('ix_spray_chemicals_spray_id'), table_name='spray_chemicals')
    op.drop_index(op.f('ix_spray_chemicals_chemical_id'), table_name='spray_chemicals')
    op.drop_index(op.f('ix_management_units_vineyard_id'), table_name='management_units')
    op.drop_index(op.f('ix_management_units_variety_id'), table_name='management_units')
    op.drop_index(op.f('ix_management_units_status_id'), table_name='management_units')
    op.drop_index(op.f('ix_chemical_group_link_group_id'), table_name='chemical_group_link')
    op.drop_index(op.f('ix_chemical_group_link_chemical_id'), table_name='chemical_group_link')
    # ### end Alembic commands ###
