"""changed vineyard name field to unique

Revision ID: a6f645baea9c
Revises: 4d1ee2a1c7da
Create Date: 2025-06-20 15:28:44.257270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a6f645baea9c'
down_revision: Union[str, Sequence[str], None] = '4d1ee2a1c7da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vineyard', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_vineyard_name'), 'vineyard', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vineyard_name'), table_name='vineyard')
    op.alter_column('vineyard', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
