"""added many to one rel

Revision ID: af3ba2641902
Revises: 51b173572aac
Create Date: 2025-06-17 17:16:28.406938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af3ba2641902'
down_revision: Union[str, Sequence[str], None] = '51b173572aac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('managementunit', sa.Column('vineyard_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'managementunit', 'vineyard', ['vineyard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'managementunit', type_='foreignkey')
    op.drop_column('managementunit', 'vineyard_id')
    # ### end Alembic commands ###
