"""added columns to Chemical

Revision ID: b91e86f28278
Revises: d5b580424b19
Create Date: 2025-06-26 12:06:36.389307

"""

import enum
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b91e86f28278"
down_revision: Union[str, Sequence[str], None] = "d5b580424b19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class MixRateUnit(enum.Enum):
    MILLILITRES = "ml"
    GRAMS = "g"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_created_date"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_last_login"), table_name="users")
    op.drop_table("users")
    mix_rate_unit_enum = sa.Enum(MixRateUnit, name="mixrateunit")
    mix_rate_unit_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "chemicals", sa.Column("mix_rate_per_100l", sa.Integer(), nullable=True)
    )
    op.add_column(
        "chemicals",
        sa.Column(
            "mix_rate_unit",
            sa.Enum("MILLILITRES", "GRAMS", name="mixrateunit"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chemicals", "mix_rate_unit")
    op.drop_column("chemicals", "mix_rate_per_100l")
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("hash_password", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_login", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
    )
    op.create_index(op.f("ix_users_last_login"), "users", ["last_login"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(
        op.f("ix_users_created_date"), "users", ["created_date"], unique=False
    )
    # ### end Alembic commands ###
