"""Changed field names in Chemical

Revision ID: bdc9cfc18136
Revises: 9c32f14551b3
Create Date: 2025-06-26 13:06:24.479333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdc9cfc18136'
down_revision: Union[str, Sequence[str], None] = '9c32f14551b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('RUST_MITE', 'BUD_MITE', 'BOTRYTIS', 'DOWNY_MILDEW', 'NUTRITION', 'POWDERY_BOT', 'POWDERY', 'WETTER', name='target').create(op.get_bind())
    op.drop_index(op.f('ix_users_created_date'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_table('users')
    op.add_column('chemicals', sa.Column('rate_per_100l', sa.Integer(), nullable=True))
    op.add_column('chemicals', sa.Column('rate_unit', postgresql.ENUM('MILLILITRES', 'GRAMS', name='mixrateunit', create_type=False), nullable=True))
    op.alter_column('chemicals', 'target',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('RUST_MITE', 'BUD_MITE', 'BOTRYTIS', 'DOWNY_MILDEW', 'NUTRITION', 'POWDERY_BOT', 'POWDERY', 'WETTER', name='target'),
               existing_nullable=True,
               postgresql_using='target::target')
    op.drop_column('chemicals', 'mix_rate_unit')
    op.drop_column('chemicals', 'mix_rate_per_100l')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chemicals', sa.Column('mix_rate_per_100l', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chemicals', sa.Column('mix_rate_unit', postgresql.ENUM('MILLILITRES', 'GRAMS', name='mixrateunit', create_type=False), autoincrement=False, nullable=True))
    op.alter_column('chemicals', 'target',
               existing_type=sa.Enum('RUST_MITE', 'BUD_MITE', 'BOTRYTIS', 'DOWNY_MILDEW', 'NUTRITION', 'POWDERY_BOT', 'POWDERY', 'WETTER', name='target'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('chemicals', 'rate_unit')
    op.drop_column('chemicals', 'rate_per_100l')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_created_date'), 'users', ['created_date'], unique=False)
    sa.Enum('RUST_MITE', 'BUD_MITE', 'BOTRYTIS', 'DOWNY_MILDEW', 'NUTRITION', 'POWDERY_BOT', 'POWDERY', 'WETTER', name='target').drop(op.get_bind())
    # ### end Alembic commands ###
