"""added spray_start_time and spray_finish_time to SprayRecord

Revision ID: c6714bb209e1
Revises: fc44eb0d6cfb
Create Date: 2025-10-01 09:07:36.433049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = 'c6714bb209e1'
down_revision: Union[str, Sequence[str], None] = 'fc44eb0d6cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spray_records', sa.Column('spray_start_time', sa.DateTime(), nullable=True))
    op.add_column('spray_records', sa.Column('spray_finish_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_spray_records_spray_finish_time'), 'spray_records', ['spray_finish_time'], unique=False)
    op.create_index(op.f('ix_spray_records_spray_start_time'), 'spray_records', ['spray_start_time'], unique=False)
    op.sync_enum_values(
        enum_schema='public',
        enum_name='target',
        new_values=['RUST_MITE', 'BUD_MITE', 'BOTRYTIS', 'DOWNY_MILDEW', 'NUTRITION', 'POWDERY_BOT', 'POWDERY', 'WETTER', 'GROWTH'],
        affected_columns=[TableReference(table_schema='public', table_name='spray_chemicals', column_name='target')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='chemicalgrouptype',
        new_values=['FUNGICIDE', 'HERBICIDE', 'INSECTICIDE', 'OTHER', 'NON'],
        affected_columns=[TableReference(table_schema='public', table_name='chemical_groups', column_name='type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='chemicalgrouptype',
        new_values=['FUNGICIDE', 'HERBICIDE', 'INSECTICIDE', 'OTHER'],
        affected_columns=[TableReference(table_schema='public', table_name='chemical_groups', column_name='type')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='target',
        new_values=['RUST_MITE', 'BUD_MITE', 'BOTRYTIS', 'DOWNY_MILDEW', 'NUTRITION', 'POWDERY_BOT', 'POWDERY', 'WETTER'],
        affected_columns=[TableReference(table_schema='public', table_name='spray_chemicals', column_name='target')],
        enum_values_to_rename=[],
    )
    op.drop_index(op.f('ix_spray_records_spray_start_time'), table_name='spray_records')
    op.drop_index(op.f('ix_spray_records_spray_finish_time'), table_name='spray_records')
    op.drop_column('spray_records', 'spray_finish_time')
    op.drop_column('spray_records', 'spray_start_time')
    # ### end Alembic commands ###
