"""added boundary polygon field

Revision ID: d11061a531f7
Revises: 32546dd66de7
Create Date: 2025-07-18 11:27:19.668033

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d11061a531f7"
down_revision: Union[str, Sequence[str], None] = "32546dd66de7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vineyards",
        sa.Column(
            "boundary",
            geoalchemy2.types.Geometry(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
    )


"""     op.create_index(
        "idx_vineyards_boundary",
        "vineyards",
        ["boundary"],
        unique=False,
        postgresql_using="gist",
    ) """
# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_vineyards_boundary", table_name="vineyards", postgresql_using="gist"
    )
    op.drop_column("vineyards", "boundary")
    # ### end Alembic commands ###
