"""Changed decimal places of row_width and vine_spacing in MUs

Revision ID: d803d4a74b7a
Revises: 756b97b30549
Create Date: 2025-06-27 17:50:05.499077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd803d4a74b7a'
down_revision: Union[str, Sequence[str], None] = '756b97b30549'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created_date'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_last_login'), table_name='users')
    op.drop_table('users')
    op.alter_column('management_units', 'row_width',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=True)
    op.alter_column('management_units', 'vine_spacing',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=2, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('management_units', 'vine_spacing',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.alter_column('management_units', 'row_width',
               existing_type=sa.Numeric(precision=2, scale=1),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=True)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_last_login'), 'users', ['last_login'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_created_date'), 'users', ['created_date'], unique=False)
    # ### end Alembic commands ###
