"""made clone_name nullable

Revision ID: fa20a2d65436
Revises: b0ff9b1240b5
Create Date: 2025-06-18 10:11:27.670880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa20a2d65436'
down_revision: Union[str, Sequence[str], None] = 'b0ff9b1240b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variety', 'clone_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variety', 'clone_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
