"""added active ingredient unit ENUM to Chemical

Revision ID: fc44eb0d6cfb
Revises: 07b02536db59
Create Date: 2025-09-10 16:26:05.792185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc44eb0d6cfb'
down_revision: Union[str, Sequence[str], None] = '07b02536db59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_ingredients', 'active_ingredient_unit')
    op.add_column('chemicals', sa.Column('active_ingredient_unit', postgresql.ENUM('GL', 'GKG', name='activeingredientunit', create_type=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chemicals', 'active_ingredient_unit')
    op.add_column('active_ingredients', sa.Column('active_ingredient_unit', postgresql.ENUM('GL', 'GKG', name='activeingredientunit', create_type=False), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
